# Generated by Django 4.1.7 on 2023-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_listing_category_alter_listing_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
