# Generated by Django 4.1.7 on 2023-07-17 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_rename_owner_listing_seller_listing_watchlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="cover_image",
            new_name="image_url",
        ),
    ]
