# Generated by Django 4.1.7 on 2023-07-17 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_rename_cover_image_listing_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="author",
        ),
    ]
