# Generated by Django 4.2.3 on 2023-07-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_category_alter_listing_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
