# Generated by Django 4.1.7 on 2023-07-19 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_bid_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="value",
            new_name="amount",
        ),
    ]
