# Generated by Django 4.1.7 on 2023-07-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_alter_listing_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
