# Generated by Django 4.1.7 on 2023-07-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0014_alter_listing_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(
                default="https://st4.depositphotos.com/14953852/24787/v/600/depositphotos_247872612-stock-illustration-no-image-available-icon-vector.jpg"
            ),
        ),
    ]
