# Generated by Django 4.1.7 on 2023-07-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0017_alter_listing_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
