# Generated by Django 4.1.7 on 2023-07-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0018_alter_listing_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(max_length=200),
        ),
    ]
