# Generated by Django 4.1.7 on 2023-07-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0019_alter_comment_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="listing",
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_listings",
                to="auctions.bid",
            ),
        ),
    ]
