# Generated by Django 4.1.7 on 2023-07-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0020_remove_bid_listing_alter_listing_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="current_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_listings",
                to="auctions.bid",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
