# Generated by Django 4.1.7 on 2023-07-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0024_listing_total_bids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="total_bids",
        ),
        migrations.AddField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_bids",
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="current_bid",
            field=models.FloatField(default=0),
        ),
    ]
