# Generated by Django 4.1.7 on 2023-07-24 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0025_remove_listing_total_bids_bid_listing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="current_bid",
        ),
    ]
